#version 460 core
layout(local_size_x = 32) in;

restrict readonly layout(std430, binding = 0) buffer DistanceBuffer {
    float in_distances[];
};
restrict readonly layout(std430, binding = 1) buffer ColorTypeBuffer {
    uint in_color_types[];
};
restrict readonly layout(std430, binding = 2) buffer WidthBuffer {
    float in_widths[];
};
restrict readonly layout(std430, binding = 3) buffer PositionBuffer {
    vec3 in_positions[];
};

restrict writeonly layout(std430, binding = 4) buffer position {
	vec3 out_positions[];
};

restrict writeonly layout(std430, binding = 5) buffer ColorDataBuffer {
	uvec2 out_colors[];
};

restrict writeonly layout(std430, binding = 6) buffer LightBuffer {
	uvec4 out_lights[];
};

restrict writeonly layout(std430, binding = 7) buffer SDFBuffer {
	vec3 out_sdf_distance[];
};

layout(location = 0) uniform mat4 VP;
layout(location = 1) uniform vec3 Eye;
layout(location = 2) uniform vec2 WH;
layout(location = 3) uniform vec3 lightDirCam;
layout(location = 4) uniform vec3 lightDirSide;

void calcLights(in uint index, in vec3 B, in vec3 C) {
    vec3 CI = normalize(B-C);
    vec3 BE = normalize(B-Eye);
    vec3 T = normalize(cross(CI,BE));
    vec3 N = normalize(cross(T,CI));

    mat3 TBN = transpose(mat3(T,CI,N));
    out_lights[index].xy = uvec2(packSnorm4x8(vec4(TBN * lightDirCam,1.0)),packSnorm4x8(vec4(TBN * lightDirSide,1.0)));
}

void packColors(in uint index, in vec3 colorB, in vec3 colorC) {
    out_colors[index] = uvec2(packUnorm4x8(vec4(colorB,1.0)),packUnorm4x8(vec4(colorC,1.0)));
}

void getColor(in uint index, out vec3 colorB, out vec3 colorC) {
    vec4 unpacked = unpackUnorm4x8(in_color_types[index+1u]);
    colorB = unpacked.xyz;
    unpacked = unpackUnorm4x8(in_color_types[index+2u]);
    colorC = unpacked.xyz;
}

void clampNDC(inout vec4 from, inout vec4 to) {
    float t0 = from.z + from.w;
    float t1 = to.z + to.w;
    if(t1 < 0.0) {
        to = mix(to, from, t1 / (t1 - t0));
    }
}

void main() {
    uint index = gl_GlobalInvocationID.x;
    uint output_index = index * 5u;
    vec4 A4 = vec4(in_positions[index]   ,1.0);
    vec4 B4 = vec4(in_positions[index+1u],1.0);
    vec4 C4 = vec4(in_positions[index+2u],1.0);
    vec4 D4 = vec4(in_positions[index+3u],1.0);
    calcLights(index,B4.xyz,C4.xyz);
    A4 = VP * A4;
    B4 = VP * B4;
    C4 = VP * C4;
    D4 = VP * D4;

    if (B4.z + B4.w < 0.0 && C4.z + C4.w < 0.0) {
        B4 = vec4(0.0/0.0);
        C4 = vec4(0.0/0.0);
    }

    vec3 color_B, color_C;
    getColor(index,color_B,color_C);
    float distace_C = in_distances[index+1u];
    float distace_B = in_distances[index+2u];


    float t0 = B4.z + B4.w;
    float t1 = C4.z + C4.w;
    if(t0 < 0.0){
        B4 = mix(B4, C4, t0 / (t0 - t1));
        distace_B = mix(distace_B, distace_C, t0 / (t0 - t1));
        color_B = mix(color_B, color_C, t0 / (t0 - t1));
    } else if(t1 < 0.0){
        C4 = mix(C4, B4, t1 / (t1 - t0));
        distace_C = mix(distace_C, distace_B, t1 / (t1 - t0));
        color_C = mix(color_C, color_B, t1 / (t1 - t0));
    }
    if (t0 < 0.0 || t1 < 0.0) { // DIRTY FIX
        t0 = B4.x + B4.w;
        t1 = C4.x + C4.w;
        if(t0 < 0.0 && t1 >= 0.0) {
            B4 = mix(B4, C4, t0 / (t0 - t1));
            distace_B = mix(distace_B, distace_C, t0 / (t0 - t1));
            color_B = mix(color_B, color_C, t0 / (t0 - t1));
            A4 = vec4(0.0/0.0);
        } else if(t1 < 0.0 && t0 >= 0.0) {
            C4 = mix(C4, B4, t1 / (t1 - t0));
            distace_C = mix(distace_C, distace_B, t1 / (t1 - t0));
            color_C = mix(color_C, color_B, t1 / (t1 - t0));
            D4 = vec4(0.0/0.0);
        }
    }
    packColors(output_index,color_B,color_C);
    clampNDC(B4,A4);
    clampNDC(C4,D4);

    float depthB = B4.z / B4.w;
    float depthC = C4.z / C4.w;
    vec2 A = fma(A4.xy/A4.w, vec2(0.5), vec2(0.5)) * WH;
    vec2 B = fma(B4.xy/B4.w, vec2(0.5), vec2(0.5)) * WH;
    vec2 C = fma(C4.xy/C4.w, vec2(0.5), vec2(0.5)) * WH;
    vec2 D = fma(D4.xy/D4.w, vec2(0.5), vec2(0.5)) * WH;

    vec3 distances = vec3(distance(A,B), distance(C,B), distance(C,D));
    const float width = in_widths[index+1u];
    out_lights[index].zw = uvec2(floatBitsToUint(width),floatBitsToUint(distances.y));

    vec2 sdf_begin = vec2(-width);
    vec3 sdf_end = vec3(distances.y + width);
    float third_sdf_side = 1.0/0.0;

    vec2 AB_dir = (A-B) / distances.x; // A <-- B C D
    vec2 CB_dir = (C-B) / distances.y; // A B --> C D
    vec2 DC_dir = (D-C) / distances.z; // A B C --> D
    

    vec2 begin_inner_offset = -CB_dir + vec2(-CB_dir.y, CB_dir.x);
    vec2 begin_outer_offset = -CB_dir - vec2(-CB_dir.y, CB_dir.x);
    vec2 end_inner_offset   =  CB_dir + vec2(-CB_dir.y, CB_dir.x);
    vec2 end_outer_offset   =  CB_dir - vec2(-CB_dir.y, CB_dir.x);
    vec2 end_outer_third_offset = vec2(1.0/0.0);

    vec2 inner_offset_ABC = (1.0/dot(vec2( AB_dir.y,-AB_dir.x),CB_dir)) * CB_dir + (1.0/dot(vec2(-CB_dir.y, CB_dir.x),AB_dir)) * AB_dir;
    if (dot(AB_dir,CB_dir) <= -0.9999) inner_offset_ABC = vec2(-CB_dir.y, CB_dir.x);
    vec2 inner_offset_BCD = (1.0/dot(vec2(-CB_dir.y, CB_dir.x),DC_dir)) * DC_dir + (1.0/dot(vec2(-DC_dir.y, DC_dir.x),-CB_dir)) * -CB_dir;
    if (dot(-CB_dir,DC_dir) <= -0.9999) inner_offset_BCD = vec2(-CB_dir.y, CB_dir.x);

    if (!any(isnan(A)) && distances.y > 1.0) {
        if (dot(AB_dir,CB_dir) <= 0.00006) {
            // OBSTUSE
            begin_inner_offset =  inner_offset_ABC;
            begin_outer_offset = -inner_offset_ABC;

            if (dot(AB_dir,CB_dir) <= -0.9999) sdf_begin = vec2(0);
            else sdf_begin = vec2(dot(begin_inner_offset,CB_dir),dot(begin_outer_offset,CB_dir))*width;
        } else {
            // ACUTE
            float AB_l = distances.x / width;
            float CB_l = distances.y / width;
            float ab = abs(dot(inner_offset_ABC,AB_dir));
            float cb = abs(dot(inner_offset_ABC,CB_dir));
            if (ab < AB_l && cb < CB_l) {
                begin_inner_offset = inner_offset_ABC;
                begin_outer_offset = -CB_dir - vec2(-CB_dir.y, CB_dir.x);

                if (dot(inner_offset_ABC, AB_dir + CB_dir) < 0.0) {
                    begin_inner_offset = -CB_dir + vec2(-CB_dir.y, CB_dir.x);
                    begin_outer_offset = -inner_offset_ABC;
                }
                sdf_begin = vec2(dot(begin_inner_offset,CB_dir),dot(begin_outer_offset,CB_dir))*width;
            }
        }
    }

    vec2 length_conversion = 2.0 / WH * width;
    out_positions[output_index]    = vec3(B4.xy + begin_inner_offset * length_conversion, depthB);
    out_positions[output_index+1u] = vec3(B4.xy + begin_outer_offset * length_conversion, depthB);
    
    if (!any(isnan(D))) {
        if (dot(-CB_dir,DC_dir) <= 0.00006) {
            // OBSTUSE
            end_inner_offset =  inner_offset_BCD;
            end_outer_offset = -inner_offset_BCD;

            sdf_end.xy = vec2(distances.y);
            if(dot(-CB_dir,DC_dir) > -0.9999) {
                sdf_end.xy = fma(vec2(dot(end_inner_offset,CB_dir),dot(end_outer_offset,CB_dir)),vec2(width),sdf_end.xy);
            }
        } else {
            // ACUTE
            float BC_l = distances.y / width;
            float DC_l = distances.z / width;
            float bc = abs(dot(inner_offset_BCD,-CB_dir));
            float dc = abs(dot(inner_offset_BCD,DC_dir));
            if (bc < BC_l && dc < DC_l) {
                end_inner_offset = inner_offset_BCD;
                end_outer_offset = CB_dir - vec2(-CB_dir.y, CB_dir.x);
                end_outer_third_offset = -DC_dir - vec2(-DC_dir.y, DC_dir.x);

                if (dot(inner_offset_BCD, -CB_dir + DC_dir) < 0.0) {
                    end_inner_offset = CB_dir + vec2(-CB_dir.y, CB_dir.x);
                    end_outer_offset = -inner_offset_BCD;
                    end_outer_third_offset = -DC_dir + vec2(-DC_dir.y, DC_dir.x);
                }
                third_sdf_side = dot(end_outer_third_offset, vec2(-CB_dir.y, CB_dir.x)) * width;

                sdf_end = fma(vec3(dot(end_inner_offset,CB_dir),dot(end_outer_offset,CB_dir),dot(end_outer_third_offset,CB_dir)),vec3(width),vec3(distances.y));
            }
        }
    }
    

    out_positions[output_index+2u] = vec3(C4.xy + end_inner_offset * length_conversion, depthC);
    out_positions[output_index+3u] = vec3(C4.xy + end_outer_offset * length_conversion, depthC);
    out_positions[output_index+4u] = vec3(C4.xy + end_outer_third_offset * length_conversion, depthC);

    float reverse = unpackUnorm4x8(in_color_types[index+2u]).a != 0.0 ? -1.0 : 1.0;
    out_sdf_distance[output_index]    = vec3(width,sdf_begin.x       , reverse * (distace_B + sdf_begin.x));
    out_sdf_distance[output_index+1u] = vec3(-width,sdf_begin.y      , reverse * (distace_B + sdf_begin.y));
    out_sdf_distance[output_index+2u] = vec3(width,sdf_end.x         , reverse * (distace_B + sdf_end.x));
    out_sdf_distance[output_index+3u] = vec3(-width,sdf_end.y        , reverse * (distace_B + sdf_end.y));
    out_sdf_distance[output_index+4u] = vec3(third_sdf_side,sdf_end.z, reverse * (distace_B + sdf_end.z));
}