#version 460 core
layout(local_size_x = 32) in;
#extension GL_GOOGLE_include_directive : require
#include "../../common_data.glsl"
// Input
restrict readonly layout(std430, binding = 0) buffer DistanceBufferIn {
    float in_distances[];
};
restrict readonly layout(std430, binding = 1) buffer ColorTypeBufferIn {
    uint in_color_types[];
};
restrict readonly layout(std430, binding = 2) buffer PositionWidthBufferIn {
    vec4 in_position_widths[];
};
// Output
restrict writeonly layout(std430, binding = 3) buffer PositionDistanceBufferOut {
	vec4 out_position_distances[];
};
restrict writeonly layout(std430, binding = 4) buffer ColorBufferOut {
	uvec2 out_color[];
};
restrict writeonly layout(std430, binding = 5) buffer SegmentBeginBufferOut {
	vec4 begin_pos_rad[];
};
restrict writeonly layout(std430, binding = 6) buffer SDFBufferOut {
	vec4 out_sdf[];
};
restrict writeonly layout(std430, binding = 7) buffer SegmentEndBufferOut {
	vec4 end_pos_rad[];
};

layout(std140, binding = 8) uniform LineUniforms {
    uint offset;
};

vec2 OctWrap(vec2 v) {
    return (1.0 - abs(v)) * sign(v);
}

vec2 Encode(vec3 n) {
    n /= dot(abs(n),vec3(1.0));
    n.xy = n.z >= 0.0 ? n.xy : OctWrap(n.xy);
    n.xy = n.xy * 0.5 + 0.5;
    return n.xy;
}

void main() {
	const uint i = gl_GlobalInvocationID.x;
    const uint out_i = i + offset;
    if (i + 3u >= in_position_widths.length()) return;
    const uint output_i = out_i * 5u;
	vec4 A4 = vec4(in_position_widths[i   ].xyz, 1.0);
    vec4 B4 = vec4(in_position_widths[i+1u].xyz, 1.0);
    const float width_pixel = in_position_widths[i+1u].w;
    vec4 C4 = vec4(in_position_widths[i+2u].xyz, 1.0);
    vec4 D4 = vec4(in_position_widths[i+3u].xyz, 1.0);

    begin_pos_rad[out_i].xyz = B4.xyz;
    end_pos_rad[out_i].xyz = C4.xyz;

    A4 = VP * A4;
    B4 = VP * B4;
    C4 = VP * C4;
    D4 = VP * D4;

    float radius_conversion = 2.0 / P[0][0] * width_pixel / width();
    begin_pos_rad[out_i].w = B4.w * radius_conversion;
    end_pos_rad[out_i].w = C4.w * radius_conversion;

    // Clipping
    if (B4.z + B4.w < 0.0 && C4.z + C4.w < 0.0) {
        B4 = vec4(0.0/0.0);
        C4 = vec4(0.0/0.0);
    }

    vec3 color_B = unpackUnorm4x8(in_color_types[i+1u]).xyz;
    vec3 color_C = unpackUnorm4x8(in_color_types[i+2u]).xyz;
    float distace_B = in_distances[i+1u];
    float distace_C = in_distances[i+2u];

    float t0 = B4.z + B4.w;
    float t1 = C4.z + C4.w;
    if(t0 < 0.0){
        B4 = mix(B4, C4, t0 / (t0 - t1));
        distace_B = mix(distace_B, distace_C, t0 / (t0 - t1));
        color_B = mix(color_B, color_C, t0 / (t0 - t1));
    } else if(t1 < 0.0){
        C4 = mix(C4, B4, t1 / (t1 - t0));
        distace_C = mix(distace_C, distace_B, t1 / (t1 - t0));
        color_C = mix(color_C, color_B, t1 / (t1 - t0));
    }
    if (t0 < 0.0 || t1 < 0.0) { // DIRTY FIX
        t0 = B4.x + B4.w;
        t1 = C4.x + C4.w;
        if(t0 < 0.0 && t1 >= 0.0) {
            B4 = mix(B4, C4, t0 / (t0 - t1));
            distace_B = mix(distace_B, distace_C, t0 / (t0 - t1));
            color_B = mix(color_B, color_C, t0 / (t0 - t1));
            A4 = vec4(0.0/0.0);
        } else if(t1 < 0.0 && t0 >= 0.0) {
            C4 = mix(C4, B4, t1 / (t1 - t0));
            distace_C = mix(distace_C, distace_B, t1 / (t1 - t0));
            color_C = mix(color_C, color_B, t1 / (t1 - t0));
            D4 = vec4(0.0/0.0);
        }
    }

    out_color[out_i] = uvec2(packUnorm4x8(vec4(color_B,1.0)),packUnorm4x8(vec4(color_C,1.0)));

    t0 = B4.z + B4.w;
    t1 = A4.z + A4.w;
    if(t1 < 0.0) A4 = mix(A4, B4, t1 / (t1 - t0));

    t0 = C4.z + C4.w;
    t1 = D4.z + D4.w;
    if(t1 < 0.0) D4 = mix(D4, C4, t1 / (t1 - t0));
    // Clipping end

    A4.xyz /= A4.w;
    B4.xyz /= B4.w;
    C4.xyz /= C4.w;
    D4.xyz /= D4.w;

    const vec2 WH = vec2(width(), height());
    // Pixel coordinates
    vec2 A = fma(A4.xy, vec2(0.5), vec2(0.5)) * WH;
    vec2 B = fma(B4.xy, vec2(0.5), vec2(0.5)) * WH;
    vec2 C = fma(C4.xy, vec2(0.5), vec2(0.5)) * WH;
    vec2 D = fma(D4.xy, vec2(0.5), vec2(0.5)) * WH;

    float l_AB = distance(A,B);
    float l_CB = distance(C,B);
    float l_DC = distance(C,D);

    vec2 dir_AB = (A - B) / l_AB; // A <-- B C D
    vec2 dir_CB = (C - B) / l_CB; // A B --> C D
    vec2 dir_BC = -dir_CB; // A B <-- C D
    vec2 dir_DC = (D - C) / l_DC; // A B C --> D

    vec2 dir_r_AB = vec2( dir_AB.y,-dir_AB.x);
    vec2 dir_r_CB = vec2(-dir_CB.y, dir_CB.x);
    vec2 dir_r_BC = dir_r_CB;
    vec2 dir_r_DC = vec2(-dir_DC.y, dir_DC.x);

    vec2 inner_offset_ABC = dot(dir_AB,dir_CB) <= -0.9999 ? dir_r_CB :
        (1.0/dot(dir_r_AB,dir_CB)) * dir_CB + (1.0/dot(dir_r_CB,dir_AB)) * dir_AB;

    vec2 inner_offset_BCD = dot(-dir_CB,dir_DC) <= -0.9999 ? dir_r_CB :
        (1.0/dot(dir_r_CB,dir_DC)) * dir_DC + (1.0/dot(dir_r_DC,-dir_CB)) * -dir_CB;

    vec2 right_offset_ABC = abs(dot(dir_AB,dir_BC)) > 0.9999 ? dir_r_AB : (dir_r_AB + dir_r_BC) / (1.0 + dot(dir_r_AB, dir_r_BC));
    vec2 right_offset_BCD = abs(dot(dir_CB,dir_DC)) > 0.9999 ? dir_r_DC : (dir_r_CB + dir_r_DC) / (1.0 + dot(dir_r_CB, dir_r_DC));

    vec2 begin_right_offset = -dir_CB + dir_r_CB;
    vec2 begin_left_offset  = -dir_CB - dir_r_CB;
    vec2 end_right_offset   =  dir_CB + dir_r_CB;
    vec2 end_left_offset    =  dir_CB - dir_r_CB;
    vec2 end_third_offset   = vec2(1.0/0.0);

    vec2 sdf_begin = vec2(-width_pixel);
    vec3 sdf_end = vec3(l_CB + width_pixel);
    float third_sdf_side = 1.0/0.0;

    vec2 dir_ABC = normalize(inner_offset_ABC);
    float cos_ABC = abs(dot(dir_AB,dir_ABC));
    float l_ABC = width_pixel * cos_ABC * inversesqrt(1.0 - cos_ABC * cos_ABC);
    bool overlap_ABC = l_ABC > l_AB || l_ABC > l_CB;
    if (!any(isnan(A)) && l_CB > 1.0) {
        if (dot(dir_AB, dir_BC) >= 0.0) {
            // OBTUSE
            begin_right_offset =  right_offset_ABC;
            begin_left_offset  = -right_offset_ABC;
        } else {
            // ACUTE
            if (!overlap_ABC) {
                float cos_half = dot(dir_r_BC, dir_ABC);
                float sin_half = inversesqrt(1.0 - cos_half * cos_half);
                float t = (1.0 - cos_half) * sin_half;
                if (dot(right_offset_ABC, inner_offset_ABC) > 0.0) {
                    begin_right_offset = inner_offset_ABC;
                    begin_left_offset = -dir_r_BC + t * dir_BC;
                } else {
                    begin_left_offset = inner_offset_ABC;
                    begin_right_offset = dir_r_BC + t * dir_BC;
                }
            }
        }
        sdf_begin = vec2(dot(begin_right_offset,dir_CB),dot(begin_left_offset,dir_CB))*width_pixel;
    }

    vec2 dir_BCD = normalize(inner_offset_BCD);
    float cos_BCD = abs(dot(dir_DC,dir_BCD));
    float l_BCD = width_pixel * cos_BCD * inversesqrt(1.0 - cos_BCD * cos_BCD);
    bool overlap_BCD = l_BCD > l_DC || l_BCD > l_CB;
    if (!any(isnan(D))) {
        if (dot(dir_DC, dir_CB) >= 0.0) {
            // OBTUSE
            end_right_offset =  right_offset_BCD;
            end_left_offset  = -right_offset_BCD;
        } else {
            // ACUTE
            if (!overlap_BCD) {
                float cos_half = dot(dir_r_BC, dir_BCD);
                float sin_half = inversesqrt(1.0 - cos_half * cos_half);
                float t = (1.0 - cos_half) * sin_half;
                if (dot(right_offset_BCD, inner_offset_BCD) > 0.0) {
                    end_right_offset =  inner_offset_BCD;
                    end_left_offset  = -dir_r_CB + t * dir_CB;
                    end_third_offset = -dir_r_DC - t * dir_DC;
                } else {
                    end_left_offset  = inner_offset_BCD;
                    end_right_offset = dir_r_CB + t * dir_CB;
                    end_third_offset = dir_r_DC - t * dir_DC;
                }
            }
        }
        third_sdf_side = dot(end_third_offset, dir_r_CB) * width_pixel;
        sdf_end = vec3(dot(end_right_offset,dir_CB),dot(end_left_offset,dir_CB),dot(end_third_offset,dir_CB)) * width_pixel;
        sdf_end += l_CB;
    }
    
    
    vec2 length_conversion = 2.0 / WH * width_pixel;
    float reverse = unpackUnorm4x8(in_color_types[i+2u]).a != 0.0 ? -1.0 : 1.0;
    out_position_distances[output_i]    = vec4(fma(length_conversion,begin_right_offset,B4.xy), B4.z, reverse * (distace_B + sdf_begin.x));
    out_position_distances[output_i+1u] = vec4(fma(length_conversion,begin_left_offset ,B4.xy), B4.z, reverse * (distace_B + sdf_begin.y));
    out_position_distances[output_i+2u] = vec4(fma(length_conversion,end_right_offset  ,C4.xy), C4.z, reverse * (distace_B + sdf_end.x));
    out_position_distances[output_i+3u] = vec4(fma(length_conversion,end_left_offset   ,C4.xy), C4.z, reverse * (distace_B + sdf_end.y));
    out_position_distances[output_i+4u] = vec4(fma(length_conversion,end_third_offset  ,C4.xy), C4.z, reverse * (distace_B + sdf_end.z));

    out_sdf[output_i]    = vec4( width_pixel,   sdf_begin.x,width_pixel,l_CB);
    out_sdf[output_i+1u] = vec4(-width_pixel,   sdf_begin.y,width_pixel,l_CB);
    out_sdf[output_i+2u] = vec4( width_pixel,   sdf_end.x,  width_pixel,l_CB);
    out_sdf[output_i+3u] = vec4(-width_pixel,   sdf_end.y,  width_pixel,l_CB);
    out_sdf[output_i+4u] = vec4( third_sdf_side,sdf_end.z,  width_pixel,l_CB);
}