#version 460 core
layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) readonly buffer PositionBuffer {
    vec4 positions[]; 
};

layout(std430, binding = 1) writeonly buffer NormalBuffer {
    vec4 normals[];
};

void main() {
    uint idx = gl_GlobalInvocationID.x * uint(3);
    if (idx + 2 >= positions.length()) return;
    
    
    vec3 v0 = positions[idx].xyz;
    vec3 v1 = positions[idx + 1].xyz;
    vec3 v2 = positions[idx + 2].xyz;

    vec3 edge1 = v0 - v1;
    vec3 edge2 = v2 - v1;

    vec3 triangleNormal = normalize(cross(edge1, edge2));
    
    normals[idx]     = vec4(triangleNormal, 0.0);
    normals[idx + 1] = vec4(triangleNormal, 0.0);
    normals[idx + 2] = vec4(triangleNormal, 0.0);
}