#version 460 core
layout(local_size_x = 128) in;

struct Data {
    uvec2 dist_col[4];
    uvec2 dist_id;
};

restrict writeonly layout(std430, binding = 11) buffer DatBuff {
    Data data[];
};

void main() {
    uint base = gl_GlobalInvocationID.x;
    if (base < data.length()) {
        for (int i = 0; i < 4; ++i)
            data[base].dist_col[i] = uvec2(0,0);
        data[base].dist_id = uvec2(0,0);
    }
}